### ISSUE TITLE
How to make commands for Line Client users

### ISSUE THREAD

**Issue by frostyshield** [carpedm20/LINE#129]
Ok so I've got the majority of this working as a Line bot, I'm just struggling how to set commands like vkick @frosty etc., is anyone able to assist in this? thanks :)

**Comment by R-N** [comment]
I'm using regex to read commands.
for example:

import re
 r = re.compile("vkick *([^ ]+)")

then when receiving message, where 'text' is the message's text

m = r.match(text)
if m:
    userId = m.group(0)

Idk about the upper level client, I've stopped using that since long ago, but in api.py you can get contact by

contact = client._client._findContactByUserid(userId)

then you get its mid by

mid = contact.id

and also get the group's mid by

groupId = receiver.id

in messages to group, the group is the receiver (to), or generally in operations, the group is  the operation's param1

then you call

client._client._kickoutFromGroup(groupId, [mid]) 

which kicks users with mid listed in contactIds, from group which mid is groupId.
know that the [] is a must, it expects a list of mids. you can kick many users at once.
where client is the LineClient instance and _client is the LineAPI instance in LineClient

the group wont be notified immediately though if you use _client. To make it be notified instantly, use _client_out which how-to you can find here somewhere in issues (which is quite confusing actually)

**Comment by frostyshield** [comment]
I'm confused how to even implement that from what you said xD I'm not the best at python to be honest lol hardly use it

**Comment by R-N** [comment]
Sorry I'm bad at explaining things, you see.

The line bot is actually the first thing I made in Python, never touched python before. Luckily I can find stuff about Python easily on the web. Not about this lib tho, gotta dig through the issues here.

Have you tried making an echo bot?

**Comment by anysz** [comment]
if msg.startswith(botname +' vkick'):
  checkingout tagged people(s)-> Kick them

**Comment by Nilpo** [comment]
You should avoid using regular expressions in a bot. They have to be compiled at runtime and that is costly in terms of microtime. The short answer, it will make your bot slower. Especially if you are using them for every command.

**Comment by R-N** [comment]
Compiling regex once every boot isnt costly, I think?

The command name 'match' isnt that costly.
First I check if the message starts with '/'
Next I get command name with regex "/([^ ]+)( ?)", then check if that command exists.
If it does, check if it requires argument, if yes, split the message by [match.span()[1]:] then parse it as argument. The parsing time depends on how you parse the argument. You may use another regex, split, or just use the rest of the message raw.
Finally, do the command. 

I think only the argument parsing may be quite costly, depends on how long the arguments are.

Of course it will make the bot slower. The more feature you add the slower it will become.

**Comment by cwkfr** [comment]
To be honest, using regex is overkill for command parsing, also regex is slow and expensive. I prefer to use string split method. Unless you want to validate user input, regex is a not a bad choice.

**Comment by frostyshield** [comment]
Figured this out thanks xD

**Comment by daniyal469** [comment]
Hi
