### ISSUE TITLE
Help me please ??? JSON Error

### ISSUE THREAD

**Issue by mxttr008** [carpedm20/LINE#29]
![line](https://cloud.githubusercontent.com/assets/5046387/7344777/0e22c29a-ecf9-11e4-96b5-6b899dcac08d.png)

**Comment by cjltsod** [comment]
It's fine when I testing today with newest code.
Is it possible you hit a firewall that prevent you connect to server?

**Comment by mxttr008** [comment]
i solve code it's new problem
![line2](https://cloud.githubusercontent.com/assets/5046387/7349476/938bf5e4-ed23-11e4-8994-3e25d184c22f.png)

**Comment by mxttr008** [comment]
i'm solve code fine new problem
![line2](https://cloud.githubusercontent.com/assets/5046387/7349496/be6d927c-ed23-11e4-9e6e-9bd9830597df.png)

**Comment by cjltsod** [comment]
You just remove `get_json` function from `api.py`. Your previous problem may still exist.

**Comment by cjltsod** [comment]
@mxttr008 : Please let us know if this issue is still exist. 
Without situation described, it's hard to guess when is this bug appears.

**Comment by Otokiru** [comment]
just today, im facing this issue as well... i can logged in using the auth token method yesterday tho...

im not sure if this is helpful but before i got this issue, i was trying to log-on into another LINE account in a seperate terminal window using a different com_name while another account is still running.

**Comment by carpedm20** [comment]
Are you using latest LINE package? If you are not sure, please try:

    pip install line --upgrade

**Comment by Otokiru** [comment]
yup, im using the latest package~

**Comment by Otokiru** [comment]
Hi all, i manage to find a way around it... Here's what i did:

I added "json.dumps(msg)" in api.py, as I'm a total noob in python, i thought it would print out the whole msg object into json so that i can do a little debugging....
![screen shot 2015-05-27 at 11 02 34 am](https://cloud.githubusercontent.com/assets/2200634/7828049/e6e442ce-0460-11e5-9250-efb3296deaec.png)

But in the end, it actually causes more errors...but hey, at least it print out useful info that i can use... like the authToken... ^ w ^ and yes, i can login using that authToken itself~
![screen shot 2015-05-27 at 11 03 30 am](https://cloud.githubusercontent.com/assets/2200634/7828067/32d3592c-0461-11e5-903d-bfd65713bbf3.png)

**Comment by carpedm20** [comment]
@Otokiru Great :smile: And now I will close this issue and further login error including json decoding exception etc will be all ignored because it is critically related to the removed code. There is various ways to re-write the removed code and I cannot give you any kind of hint related to this. For example, maybe sometimes you don't have to make a working code completely to get AuthToken like the case of @Otokiru Any way, good luck and may the line be with you :smiley:

**Comment by cjltsod** [comment]
@Otokiru : You can simply `print(object)` to print what you want. Not all objects in python can be dump as `json.dumps`, but print is okay for most of python objects. You can also use `dir(object)` to check what methods and properties can be used. If you want to get the token, just simply look into property `client.authToken`
Please let us know that without adding `json.dumps` in api.py would still cause the issue or not.

**Comment by Otokiru** [comment]
@cjltsod Okay thanks for the advice!~
