### ISSUE TITLE
Error with updateAuthToken

### ISSUE THREAD

**Issue by materaj** [carpedm20/LINE#31]
Hi,

I got the error "Exception: Error: You need to login first. There is no valid certificate" when I use client.updateAuthenToken. What should I do to solve this error.

Traceback (most recent call last):
  File "./line-client.py", line 39, in <module>
    client.updateAuthToken()
  File "/usr/local/lib/python2.7/dist-packages/line-0.5.1-py2.7.egg/line/api.py", line 73, in updateAuthToken
    self.raise_error("You need to login first. There is no valid certificate")
  File "/usr/local/lib/python2.7/dist-packages/line-0.5.1-py2.7.egg/line/api.py", line 294, in raise_error
    raise Exception("Error: %s" % msg)
Exception: Error: You need to login first. There is no valid certificate

**Comment by cjltsod** [comment]
It's because you are using authToken to create client.
updateAuthToken runs login process to update token. updateAuthToken without login information (username, and password) is impossible. 
Try to login with username and password, or set the necessary information to client can avoid this exception.

**Comment by materaj** [comment]
Thank you :)

**Comment by carpedm20** [comment]
Thanks @cjltsod

**Comment by wldtw2008** [comment]
I got the same error message when I try to send some txt msg to the group which I didn't join it.

The condition is:
* A is me (python line package)
* B is other person
* B create a group named GGG, and invite A into GGG. but A  forget to accept it.
The situation is:
*A use line python login (via authtoken) is ok. 
*A do list client.groups , the result will contain GGG, for example, print(client.groups[0].name)  it shows GGG. (That means A is a member of group GGG, but it should not, because A doesn't yet accept the invite)
*Then, if A try to send some message to group GGG, for example,  client.groups[0].sendMessage("Hello, I'm ready!"), 
It will raise:   
File "build/bdist.linux-i686/egg/line/models.py", line 68, in sendMessage
Exception: Error: You need to login first. There is no valid certificate
---
After A accept the invite, be a member of group GGG, everything is working good!
---
hope this information is useful~
By the way, thank carpedm20 very much, the package is awesome!

**Comment by royl2k90** [comment]
So the line.crt was at Python27 directory and not LINE directory itself. I deleted the LINE directory and line.crt and did a fresh pip installation of LINE via Git Bash.

`$ pip install line && pip uninstall -y line`
`$ git clone https://github.com/carpedm20/LINE.git`
`$ cd LINE/line`
`$ wget https://gist.github.com/windows98SE/b739038218b6fe4d423f/raw/5f68cf3d9a2a88576b739810a6bd6fcaa0c5e940/api.py.patch --no-check-certificate`
`$ patch api.py < api.py.patch`
`$ cd ..`
`$ python config.py`
`$ python setup.py install`

Then I launched Python27 command line, import LineClient and login with email and password. Then I am prompted to key in a PIN into my phone. This is the moment when line.crt is generated in Python27 directory.

Next, I printed out the current client authentication token. At this point, I am not supposed to point my current token to the client object otherwise it will throw an exception if I were to update the current token. That's because my login info (email and pwd) has been overwritten by the current token.

Right after I enter the first PIN, I am supposed to update the current token using the existing client object's login info (email and pwd). Then enter another different PIN into my phone and point back the updated token to my client object.

The picture below would illustrate the above 3 paragraphs.

![loginauthline](https://cloud.githubusercontent.com/assets/14073474/15670336/77a1054e-2757-11e6-8f01-d58f51c7d11f.png)
